name: flutter_ecommerce
description: E-Commerce Whitelabel Application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  equatable: ^2.0.5

  # Network
  http: ^1.1.0
  dartz: ^0.10.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^7.6.4

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
